export default {
    "strengthRatings": [
        "Compromesso",
        "Molto debole",
        "Debole",
        "Medio",
        "Forte",
        "Molto forte"
    ],
    "tooShort": "Troppo corto",
    "enterAPassword": "Scegli una password",
    "passwordStrength": "Sicurezza password",
    "poweredBy": "offerto da",
    "breachedPasswordMessage": "Questa password è noto per hacker e <b><u>non deve essere usato</u></b>. E 'stato esposto al pubblico in una o più delle violazioni dei dati in questi ultimi anni (LinkedIn, MySpace, Yahoo, etc.)<br/><br/>We <b><u>fortemente</u></b> consiglia si sceglie una password diversa e interrompere l'uso di questo.",
    "hackedPasswordMessage": "Questa password è noto per hacker e <b><u>non deve essere usato</u></b>. Si trova in comune di password dizionari di cracking.<br/><br/>We <b><u>fortemente</u></b> consiglia di scegliere una password diversa e interrompere l'uso di questo.",
    "suggestion": "Suggerimenti",
    "suggestions": {
        "defaultFeedback": "Utilizzare un paio di parole, evitare frasi comuni",
        "defaultFeedback2": "Non c'è bisogno di simboli, cifre o lettere maiuscole",
        "addWord": "Aggiungere un'altra parola o due. parole non comuni sono migliori.",
        "rowsOfKeys": "File diritte di tasti sono facili da indovinare",
        "shortKeyboardPatterns": "Modelli di tastiera brevi sono facili da indovinare",
        "longerKeyboardPattern": "Utilizzare un modello di tastiera più a lungo con più giri",
        "shortRepeats": "Ripete come \"aaa\" sono facili da indovinare",
        "longRepeats": "Ripete come \"abcabcabc\" sono solo leggermente più difficile da indovinare di \"abc\"",
        "avoidRepeatedWords": "Evitare le parole e caratteri ripetuti",
        "avoidSequences": "Sequenze come ABC o 6543 sono facili da indovinare",
        "avoidSequences2": "Evitare sequenze",
        "recentYears": "Negli ultimi anni sono facili da indovinare",
        "avoidRecentYears": "Evitare questi ultimi anni",
        "avoidAssociatedYears": "Evitare di anni che sono associati con voi",
        "datesAreEasy": "Le date sono spesso facili da indovinare",
        "avoidAssociatedDates": "Evitare le date e gli anni che sono associati con voi",
        "similarToCommon": "Questo è simile a una password comunemente usato",
        "topTenPassword": "Questo è un top-10 password comune",
        "top100Password": "Si tratta di una password comune top-100",
        "veryCommonPassword": "Questa è una password molto comune",
        "wordByItself": "Una parola di per sé è facile da indovinare",
        "namesByThemselves": "Nomi e cognomi di per sé sono facili da indovinare",
        "commonNamesAndSurnames": "I nomi comuni e cognomi sono facili da indovinare",
        "capitalization": "La capitalizzazione non aiuta molto",
        "allUpperCase": "All-maiuscolo è quasi altrettanto facile intuire come tutto in minuscolo",
        "reversedWords": "Parole invertite non sono molto più difficili da indovinare",
        "predictableSubs": "Sostituzioni prevedibili come '@' invece di 'un' non aiutano molto",
        "allNumbers": "Le password composte da tutti i numeri sono facili da indovinare"
    }
};