export default {
    "strengthRatings": [
        "Compromis",
        "Très faible",
        "Faible",
        "Moyen",
        "Fort",
        "Très fort"
    ],
    "tooShort": "Trop court",
    "enterAPassword": "Choisissez un mot de passe",
    "passwordStrength": "Fiabilité du mot de passe",
    "poweredBy": "alimenté par",
    "hackedPasswordTitle": "Mot de Passe Compromis",
    "breachedPasswordMessage": "Ce mot de passe est connu pour les pirates et les <b><u>ne doit pas être utilisé</u></b>. Il a été exposé publiquement dans un ou plusieurs des violations de données au cours des dernières années.<br/><br/>We <b><u>fortement</u></b> recommander vous choisissez un mot de passe différent et cesser l'utilisation de celui-ci.",
    "hackedPasswordMessage": "Ce mot de passe est connu pour les pirates et les <b><u>ne doit pas être utilisé</u></b>. Il se trouve dans le mot de passe commun dictionnaires de craquage.<br/><br/>We <b><u>fortement</u></b> vous recommandons de choisir un mot de passe différent et cesser l'utilisation de celui-ci.",
    "suggestion": "Suggestions",
    "suggestions": {
        "defaultFeedback": "Utilisez quelques mots, éviter des phrases courantes",
        "defaultFeedback2": "Pas besoin de symboles, de chiffres ou de lettres majuscules",
        "addWord": "Ajouter un autre mot ou deux. mots peu fréquents sont mieux.",
        "rowsOfKeys": "Lignes droites de touches sont faciles à deviner",
        "shortKeyboardPatterns": "Modèles de clavier courts sont faciles à deviner",
        "longerKeyboardPattern": "Utilisez un modèle de clavier plus avec plusieurs tours",
        "shortRepeats": "Répétitions comme \"aaa\" sont faciles à deviner",
        "longRepeats": "Répétitions comme \"ABCABCABC\" ne sont que légèrement plus difficile à deviner que \"abc\"",
        "avoidRepeatedWords": "Évitez les mots et les caractères répétés",
        "avoidSequences": "Sequences comme abc ou 6543 sont faciles à deviner",
        "avoidSequences2": "Évitez les séquences",
        "recentYears": "Ces dernières années, sont faciles à deviner",
        "avoidRecentYears": "Évitez ces dernières années",
        "avoidAssociatedYears": "Évitez années qui sont associées avec vous",
        "datesAreEasy": "Les dates sont souvent faciles à deviner",
        "avoidAssociatedDates": "Évitez les dates et les années qui sont associées avec vous",
        "similarToCommon": "Ceci est similaire à un mot de passe couramment utilisés",
        "topTenPassword": "Ceci est un top-10 mot de passe commun",
        "top100Password": "Ceci est un mot de passe commun top-100",
        "veryCommonPassword": "Ceci est un mot de passe très commun",
        "wordByItself": "Un mot en lui-même est facile à deviner",
        "namesByThemselves": "Les noms et prénoms par eux-mêmes sont faciles à deviner",
        "commonNamesAndSurnames": "Noms et prénoms communs sont faciles à deviner",
        "capitalization": "Capitalisation ne contribue pas beaucoup",
        "allUpperCase": "Tout en majuscules est presque aussi facile à deviner en minuscules",
        "reversedWords": "Mots Inversée ne sont pas beaucoup plus difficile à deviner",
        "predictableSubs": "Substitutions prévisibles comme '@' au lieu de 'a' n'aident pas beaucoup",
        "allNumbers": "Les mots de passe composés de tous les chiffres sont faciles à deviner"
    }
};