export default {
    "strengthRatings": [
        "Comprometida",
        "Muy débil",
        "Débil",
        "Medio",
        "Fuerte",
        "Muy fuerte"
    ],
    "tooShort": "Demasiado corto",
    "enterAPassword": "Elije una contraseña",
    "passwordStrength": "Seguridad de la contraseña",
    "poweredBy": "impulsado por",
    "breachedPasswordMessage": "Esta contraseña se conoce a los hackers y <b><u>no debe utilizarse</u></b>. Fue expuesta públicamente en una o más de las violaciones de datos en los últimos años (LinkedIn, MySpace, Yahoo, etc.)<br/><br/>We <b><u>fuertemente</u></b> recomiendan elige una contraseña diferente y suspender el uso de éste.",
    "hackedPasswordMessage": "Esta contraseña se conoce a los hackers y <b><u>no debe utilizarse</u></b>. Se encuentra en los diccionarios de robo de contraseñas comunes. <br/><br/>We <b><u>fuertemente</u></b> recomienda elegir una contraseña diferente y suspender el uso de éste.",
    "suggestion": "Sugerencias",
    "suggestions": {
        "defaultFeedback": "Utilizar algunas palabras, evitar frases comunes",
        "defaultFeedback2": "No hay necesidad de símbolos, dígitos o letras mayúsculas",
        "addWord": "Añadir una o dos palabras. palabras poco comunes son mejores.",
        "rowsOfKeys": "Filas rectas de teclas son fáciles de adivinar",
        "shortKeyboardPatterns": "Patrones de teclado cortos son fáciles de adivinar",
        "longerKeyboardPattern": "Utilice un patrón de teclado ya con más vueltas",
        "shortRepeats": "Repite como \"aaa\" son fáciles de adivinar",
        "longRepeats": "Repite como \"abcabcabc\" son sólo un poco más difícil de adivinar que \"abc\"",
        "avoidRepeatedWords": "Evitar las palabras y caracteres repetidos",
        "avoidSequences": "Secuencias como abc o 6543 son fáciles de adivinar",
        "avoidSequences2": "Evitar secuencias",
        "recentYears": "En los últimos años son fáciles de adivinar",
        "avoidRecentYears": "Evitar los últimos años",
        "avoidAssociatedYears": "Evitar años que se asocian con usted",
        "datesAreEasy": "Las fechas son a menudo fáciles de adivinar",
        "avoidAssociatedDates": "Evitar fechas y años que se asocian con usted",
        "similarToCommon": "Esto es similar a una contraseña de uso general",
        "topTenPassword": "Se trata de una contraseña común-top 10",
        "top100Password": "Se trata de una contraseña común top-100",
        "veryCommonPassword": "Esta es una contraseña muy común",
        "wordByItself": "Una palabra de por sí es fácil de adivinar",
        "namesByThemselves": "Los nombres y apellidos que por sí mismos son fáciles de adivinar",
        "commonNamesAndSurnames": "Nombres y apellidos comunes son fáciles de adivinar",
        "capitalization": "La capitalización no ayuda mucho",
        "allUpperCase": "Todo en mayúsculas es casi tan fácil de adivinar como en minúsculas",
        "reversedWords": "Palabras invertidas no son mucho más difíciles de adivinar",
        "predictableSubs": "Sustituciones predecibles como \"@\" en lugar de \"a\" no ayudan mucho",
        "allNumbers": "Las contraseñas que constan de todos los números son fáciles de adivinar"
    }
};