export default {
    "strengthRatings": [
        "Hacked",
        "Very Weak",
        "Weak",
        "Medium",
        "Strong",
        "Very Strong"
    ],
    "tooShort": "Too Short",
    "enterAPassword": "Choose a password",
    "passwordStrength": "Password Strength",
    "poweredBy": "powered by",
    "hackedPasswordTitle": "Compromised or \"Hacked\" Password",
    "breachedPasswordMessage": "This password is known to hackers and <b><u>should not be used</u></b>. It has been exposed publicly in one or more data breaches.<br/><br/>Choose a different password and discontinue usage of this one.",
    "hackedPasswordMessage": "This password is known to hackers and <b><u>should not be used</u></b>. It is found in common password cracking dictionaries.<br/><br/>Choose a different password and discontinue usage of this one.",
    "suggestion": "Suggestions",
    "suggestions": {
        "defaultFeedback": "Use a few words, avoid common phrases",
        "defaultFeedback2": "No need for symbols, digits, or uppercase letters",
        "addWord": "Add another word or two. Uncommon words are better.",
        "rowsOfKeys": "Straight rows of keys are easy to guess",
        "shortKeyboardPatterns": "Short keyboard patterns are easy to guess",
        "longerKeyboardPattern": "Use a longer keyboard pattern with more turns",
        "shortRepeats": "Repeats like \"aaa\" are easy to guess",
        "longRepeats": "Repeats like \"abcabcabc\" are only slightly harder to guess than \"abc\"",
        "avoidRepeatedWords": "Avoid repeated words and characters",
        "avoidSequences": "Sequences like abc or 6543 are easy to guess",
        "avoidSequences2": "Avoid sequences",
        "recentYears": "Recent years are easy to guess",
        "avoidRecentYears": "Avoid recent years",
        "avoidAssociatedYears": "Avoid years that are associated with you",
        "datesAreEasy": "Dates are often easy to guess",
        "avoidAssociatedDates": "Avoid dates and years that are associated with you",
        "similarToCommon": "This is similar to a commonly used password",
        "topTenPassword": "This is a top-10 common password",
        "top100Password": "This is a top-100 common password",
        "veryCommonPassword": "This is a very common password",
        "wordByItself": "A word by itself is easy to guess",
        "namesByThemselves": "Names and surnames by themselves are easy to guess",
        "commonNamesAndSurnames": "Common names and surnames are easy to guess",
        "capitalization": "Capitalization doesn't help very much",
        "allUpperCase": "All-uppercase is almost as easy to guess as all-lowercase",
        "reversedWords": "Reversed words aren't much harder to guess",
        "predictableSubs": "Predictable substitutions like '@' instead of 'a' don't help very much",
        "allNumbers": "Passwords consisting of all numbers are easy to guess"
    }
};