export default {
    "strengthRatings": [
        "Comprometido",
        "Muito fraco",
        "Fraco",
        "Médio",
        "Forte",
        "Muito forte"
    ],
    "tooShort": "Muito curto",
    "enterAPassword": "Escolha uma senha",
    "passwordStrength": "Força da senha",
    "poweredBy": "distribuído por",
    "breachedPasswordMessage": "Esta senha é conhecida por hackers e <b><u>não deve ser usado</u></b>. Ele foi exposto ao público em uma ou mais das violações de dados nos últimos anos (LinkedIn, MySpace, Yahoo, etc.)<br/><br/>We <b><u>fortemente</u></b> recomendar -lo a escolher uma senha diferente e descontinuar o uso de um presente.",
    "hackedPasswordMessage": "Esta senha é conhecida por hackers e <b><u>não deve ser usado</u></b>. Pode ser encontrada nos dicionários de craqueamento comum de senha.<br/><br/>We <b><u>fortemente</u></b> recomendamos que você escolha uma senha diferente e descontinuar o uso de um presente.",
    "suggestion": "Sugestões",
    "suggestions": {
        "defaultFeedback": "Use poucas palavras, evite frases comuns",
        "defaultFeedback2": "Não há necessidade de símbolos, dígitos ou letras maiúsculas",
        "addWord": "Adicionar outra palavra ou dois. palavras incomuns são melhores.",
        "rowsOfKeys": "Linhas retas de teclas são fáceis de adivinhar",
        "shortKeyboardPatterns": "Padrões do teclado curtas são fáceis de adivinhar",
        "longerKeyboardPattern": "Use um padrão de teclado mais tempo com mais voltas",
        "shortRepeats": "Repete como \"aaa\" são fáceis de adivinhar",
        "longRepeats": "Repete como \"abcabcabc\" são apenas um pouco mais difícil de adivinhar do que \"abc\"",
        "avoidRepeatedWords": "Evite palavras repetidas e personagens",
        "avoidSequences": "Sequências como abc ou 6543 são fáceis de adivinhar",
        "avoidSequences2": "Evite sequências",
        "recentYears": "Nos últimos anos, são fáceis de adivinhar",
        "avoidRecentYears": "Evitar últimos anos",
        "avoidAssociatedYears": "Evitar anos que estão associados ao utilizador",
        "datesAreEasy": "As datas são muitas vezes mais fácil de adivinhar",
        "avoidAssociatedDates": "Evite datas e anos que estão associados com você",
        "similarToCommon": "Isto é semelhante a uma palavra-passe utilizada",
        "topTenPassword": "Esta é uma senha comum top-10",
        "top100Password": "Esta é uma senha comum top-100",
        "veryCommonPassword": "Esta é uma senha muito comum",
        "wordByItself": "Uma palavra por si só é fácil de adivinhar",
        "namesByThemselves": "Nomes e sobrenomes por si só são fáceis de adivinhar",
        "commonNamesAndSurnames": "Nomes comuns e sobrenomes são fáceis de adivinhar",
        "capitalization": "Capitalização não ajuda muito",
        "allUpperCase": "All-maiúscula é quase tão fácil de adivinhar como all-minúsculas",
        "reversedWords": "Palavras invertidas não são muito mais difíceis de adivinhar",
        "predictableSubs": "Substituições previsíveis, como '@' em vez de 'a' não ajuda muito",
        "allNumbers": "As senhas compostas por todos os números são fáceis de adivinhar"
    }
};