export default {
    "strengthRatings": [
        "Kompromittiert",
        "Sehr schwach",
        "Schwach",
        "Mittel",
        "Stark",
        "Sehr stark"
    ],
    "tooShort": "Zu kurz",
    "enterAPassword": "Lege ein Passwort fest",
    "passwordStrength": "Passwortstärke",
    "poweredBy": "unterstützt von",
    "breachedPasswordMessage": "Dieses Passwort wird für Hacker bekannt und <b><u>sollten nicht verwendet werden</u></b>. Es wurde in einem oder mehreren der Datenschutzverletzungen in den letzten Jahren öffentlich ausgesetzt (LinkedIn, MySpace, Yahoo, etc.)<br/><br/>Wir <b><u>stark</u></b> empfehlen Sie wählen ein anderes Passwort und beenden Nutzung dieser.",
    "hackedPasswordMessage": "Dieses Passwort wird für Hacker bekannt und <b><u>sollten nicht verwendet werden</u></b>. Es wird gemeinsam Passwort-Knack-Wörterbücher gefunden.<br/><br/>Wir <b><u>stark</u></b> empfehlen Sie ein anderes Passwort wählen und einstellen Nutzung dieser.",
    "suggestion": "Vorschläge",
    "suggestions": {
      "defaultFeedback": "Verwenden Sie ein paar Worte, vermeiden gemeinsame Phrasen",
      "defaultFeedback2": "Keine Notwendigkeit für Symbole, Ziffern oder Großbuchstaben",
      "addWord": "Einen weiteren hinzufügen Wort oder zwei. Gelegentlich Wörter sind besser.",
      "rowsOfKeys": "Gerade Reihen von Tasten sind leicht zu erraten",
      "shortKeyboardPatterns": "Kurze Tastatur-Muster sind leicht zu erraten",
      "longerKeyboardPattern": "Verwenden Sie eine längere Tastaturmuster mit mehr Windungen",
      "shortRepeats": "Wiederholt wie \"aaa\" sind leicht zu erraten",
      "longRepeats": "Wiederholt wie \"abcabcabc\" sind nur etwas schwieriger zu erraten als \"abc\"",
      "avoidRepeatedWords": "Vermeiden Sie wiederholte Wörter und Zeichen",
      "avoidSequences": "Sequenzen wie abc oder 6543 sind leicht zu erraten",
      "avoidSequences2": "Vermeiden Sequenzen",
      "recentYears": "Die letzten Jahre sind leicht zu erraten",
      "avoidRecentYears": "Vermeiden Sie den letzten Jahren",
      "avoidAssociatedYears": "Vermeiden Jahren, die mit Ihnen verbunden sind",
      "datesAreEasy": "Termine sind oft leicht zu erraten",
      "avoidAssociatedDates": "Vermeiden Sie Termine und Jahre, die mit Ihnen verbunden sind",
      "similarToCommon": "Dies ist ähnlich wie bei einem häufig verwendeten Kennwort",
      "topTenPassword": "Dies ist ein Top-10 gemeinsames Passwort",
      "top100Password": "Dies ist ein Top-100 gemeinsames Passwort",
      "veryCommonPassword": "Dies ist ein sehr gemeinsames Passwort",
      "wordByItself": "Ein Wort selbst ist leicht zu erraten",
      "namesByThemselves": "Namen und Vornamen von ihnen selbst sind leicht zu erraten",
      "commonNamesAndSurnames": "Häufige und Nachnamen sind leicht zu erraten",
      "capitalization": "Kapitalisierung hilft nicht sehr viel",
      "allUpperCase": "All-Groß ist fast so einfach wie all-Klein zu erraten",
      "reversedWords": "Umgekehrt Worte sind nicht viel schwieriger zu erraten",
      "predictableSubs": "Vorhersehbare Substitutionen wie '@' anstelle von 'a' nicht sehr viel helfen",
      "allNumbers": "Passwörter, die aus allen Zahlen bestehen, sind leicht zu erraten"
    }
};