// generated by build_frequency_lists.py
const frequency_lists = {
  passwords: [],
  english_wikipedia: [],
  female_names: [],
  surnames: [],
  us_tv_and_film: [],
  male_names: []
};
module.exports = frequency_lists;
